---
title: "Syllabus for STATS/DATASCI 531 (Winter 2021) <br><it>Analysis of Time Series</it>"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    toc: no
csl: ecology.csl
---


## Course information

* Class is online. Activities include the following.
    + asynchronous lectures (approximately 120 minutes per week)
    + 25 minute per week small group meeting with professor or GSI, scheduled during class time (Tu/Th 10-11:30am)
    + 25 minute per week small group meeting without an instructor, scheduled during class time (Tu/Th 10-11:30am)
    + homework
    + [Piazza discussion forum](https://piazza.com/umich/winter2021/statsdatasci531)
    + group midterm project, with individual peer review
    + group final project, with individual peer review
    

* Contact information:
    + E-mail: ionides@umich.edu 
    + Web: dept.stat.lsa.umich.edu/~ionides

* GSI: Baekjin Kim <baekjin@umich.edu>
    + Computing support: If you have a coding problem you cannot debug, it is often helpful to develop a simple reproducible example that others can run to you help. You can share this, and the error message you obtain, with your group and/or on Piazza, or by email if necessary.

* Office hours: Most questions about homework, lectures and other course activities should be addressed during group meetings or on Piazza. Please email the instructor or GSI if an issue arises that requires an individual meeting.

* Course notes and lectures are posted at https://ionides.github.io/531w20/ with source files available at https://github.com/ionides/531w21

* Supplementary textbook: R. Shumway and D. Stoffer "Time Series Analysis and its Applications" 4th edition. 
A pdf is available using the UM Library's Springer subscription.
An updated pdf is available free from [David Stoffer's website](http://www.stat.pitt.edu/stoffer/tsa4/tsa4.pdf)

* Pre-requisites:
    + Theoretical statistics. STATS 510 or STATS 426 or equivalent. For review, see "Mathematical Statistics and Data Analysis" by J. A. Rice. 
    + Linear algebra. A certain amount of basic linear algebra will be required. For review, see 
[www.sosmath.com/matrix/matrix.html](http://www.sosmath.com/matrix/matrix.html).
    + R programming. There is no formal R prerequisite, but we will be working with R extensively and so you should allow extra time for this course if you are new to R programming. Come to chat and we can make a plan for learning R in the context of your computational background.

-----------



## Course outline


1. Introduction to time series analysis.

2. Time series models, trend and autocovariance.

3. Stationarity, white noise, and some basic time series models.

4. Linear time series models and the algebra of autoregressive moving average (ARMA) models.

5. Parameter estimation and model identification for ARMA models.

6. Extending the ARMA model: Seasonality and trend.

7. Introduction to the frequency domain.

8. Smoothing in the time and frequency domains.

9. Introduction to partially observed Markov process models.

10. Statistical methodology for nonlinear partially observed Markov process (POMP) models.

11. Dynamic models and their simulation by Euler’s method.

12. Practical likelihood-based inference for POMP models.

13. POMP models with covariates, and a case study of polio transmission.

14.  A case study using POMP modeling to study financial volatility.

--------------

## Groups

* Groups for the first half-semester will be randomly assigned, and will work together up to and including the midterm project.

* Groups will be re-randomized after the midterm project. The new groups will work together up to and including the final project.

* Groups are expected to meet up for at least 25 minutes a week, to discuss class notes or homework or projects, and for another 25 minutes a week together with an instructor. Active participation in your group will carry course credit.

-------------

##  Grading

* Weekly homeworks (25\%).
* A group midterm project (20\%, due 11:59pm on Mon 3/8). In special situations, you can request to write an individual project for the midterm and/or the final project. This may be appropriate if you have a particular dataset or scientific question that has motivated your interest in learning time series analysis. You can also ask your group if it is willing to join collaboratively on your project to make it a group project.
* Two individual anonymous peer review evaluations of other group midterm projects (5\%, due 11:59pm on Mon 3/15). Each should be about 500 words, and should identify the main strengths and weaknesses of the project (from both technical and conceptual perspectives) as well as identifying points with room for improvement.
* A group final project (30%, due 11:59pm on 4/20).
* Two individual anonymous peer review evaluations of other group final projects (10\%, due 11:59pm on 4/29). Each should be about 1000 words, and should identify the main strengths and weaknesses of the project (from both technical and conceptual perspectives) as well as identifying points with room for improvement.
* Participation (10%). To build community for an online course, attendance and contributions in group meetings are valuable. Similarly, both raising and answering questions on a discussion forum is helpful.
* Course letter grades are anticipated to be mostly in the A, A-, B+ range customary for courses at this level. In the past, this has corresponded to overall scores of approximately 95% for A+, 90% for A, 85% for A-, 75% for B+. However, the exact cutoff used will be determined in the context of the course for this specific semester.

Each homework will have a question asking about sources. You will be asked to explain which parts of your responses above made use of a source, meaning anything or anyone you consulted (including classmates or office hours) to help you write or check your answers. All sources are permitted, but failure to attribute material from a source is plagiarism, which is unethical and may have serious consequences. **Directly copied text must be in quotation marks. Directly copied equations must be explicitly referenced to the source. The reader should not have to carry out detective work to figure out correctly which parts of the homework are attributable to a source.** Careful attribution of sources is fundamental to good scholarship, and it also facilitates meaningful grading given the reality of abundant sources. The grader will look for an honest effort applied to the homework, with contributions that go beyond the sources, following the <a href="rubric_homework.html">posted rubric</a>.

The midterm and final project will also have a substantial grading component allocated to clear and scholarly assignment of credit to sources.

----

## Student Mental Health and Wellbeing

University of Michigan is committed to advancing the mental health and wellbeing of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of support, services are available. For help, contact Counseling and Psychological Services (CAPS) at 734.764.8312 and  https://caps.umich.edu during and after hours, on weekends and holidays. You may also consult University Health Service (UHS) at 734.764.8320 and https://www.uhs.umich.edu/mentalhealthsvcs.

----------

